- hosts: localhost
  gather_facts: no
  vars:
   host: "172.16.0.1"
   username: "admin"
   password: ""
   urls_from_file: "{{ lookup('file','{{ file }}') | from_json }}"
   vdom: "root"
   ssl_verify: False

  tasks:

  - name: "set url table"
    fortiosconfig:
     config: "webfilter urlfilter"
     action: "set"
     host: "{{ host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     vdom: "{{ vdom }}"
     ssl_verify: "{{ ssl_verify }}"

     config_parameters:
       id: "1"
       json:
         entries: "{{ urls_from_file }}"

  - name: "check current url table"
    fortiosconfig:
     config: "webfilter urlfilter"
     action: "get"
     host: "{{ host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     vdom: "{{ vdom }}"
     ssl_verify: "{{ ssl_verify }}"

     config_parameters:
       id: "1"
    register: url_table_state

  - debug:
      msg: "URL loaded/in-file: [{{ url_table_state.meta.results.0.entries | length }} / {{ urls_from_file | length }}]"
